apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medinsights

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: prod

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

replicas:
  - name: auth-service
    count: 3  # High availability in production
